#!python
"""Update NetCDF metadata from a YAML file.

WARNING: THIS SCRIPT MODIFIES THE ORIGINAL FILE.

See README for details of update specification file (YAML format).
"""
from argparse import ArgumentParser

from netCDF4 import Dataset
import yaml

from dp.update_metadata import logger, process


def main(args):
    with open(args.updates) as ud:
        updates = yaml.safe_load(ud)

    logger.info('NetCDF file: {}'.format(args.ncfile))
    with Dataset(args.ncfile, mode='r+') as nc:
        for target_name in updates:
            if target_name == 'global':
                target = nc
                logger.info("Global attributes:")
            else:
                target = nc.variables[target_name]
                logger.info("Attributes of variable '{}':".format(target_name))

            process(target, updates[target_name])


if __name__ == '__main__':
    parser = ArgumentParser(
        description='Update NetCDF file attributes based on an updates '
                    'specification file')
    parser.add_argument(
        '-u', '--updates', required=True,
        help='File containing updates'
    )
    parser.add_argument(
        'ncfile',
        help='NetCDF file to update'
    )
    args = parser.parse_args()
    main(args)
