name: Lint

on: push

jobs:
  black:

    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          black_args: ". --check"