name: Python CI

on: push

jobs:
  test:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
        sudo apt-get install cdo

    - name: Install poetry
      run: |
        wget -O - https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install python dependencies
      run: |
        poetry install --with=dev
    
    - name: Test with pytest (full)
      if: github.ref == 'refs/heads/master'
      run: |
        poetry run py.test -m "not online" -v
    
    - name: Test with pytest (fast)
      if: github.ref != 'refs/heads/master'
      run: |
        poetry run py.test -m "not online and not slow" -v
